class MyException extends Exception
{
	private int detail;
	
	MyException(int a)
	{
		detail=a;
	}
}

class ThrowDemo
{
	static void demoproc()
	{
		try
		{
			throw new NullPointerException("demo");
			throw new MyException("6");
		}
		catch(NullPointerException e)
		{
			System.out.println("Inside demoproc");
			throw(e);
		}
	}
	
	public static void main(String args[])
	{
		try
		{
			demoproc();
		}
		catch(NullPointerException e)
		{
			System.out.println("Recaught"+e);
		}
	}
}
